const SERVER_RESPONSE_400 = {
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  TOKEN_EXPIRED: 419,
  NO_TOKEN: 406
};

const SERVER_RESPONSE_SUCCESS = {
  SUCCESS: 200,
  CREATED: 201
};

const SERVER_RESPONSE_500 = {
  INTERNAL_SERVER_ERROR: 500
};

const combinedResponses = {
  ...SERVER_RESPONSE_400,
  ...SERVER_RESPONSE_SUCCESS,
  ...SERVER_RESPONSE_500
};

export const {
  BAD_REQUEST,
  UNAUTHORIZED,
  FORBIDDEN,
  NOT_FOUND,
  TOKEN_EXPIRED,
  NO_TOKEN,
  INTERNAL_SERVER_ERROR,
  SUCCESS,
  CREATED
} = combinedResponses;
